function MIRcatDeclareGlobalVars()

global MIRcatSDK_RET_SUCCESS; MIRcatSDK_RET_SUCCESS = uint32(0);
global MIRcatSDK_RET_UNSUPPORTED_TRANSPORT; MIRcatSDK_RET_UNSUPPORTED_TRANSPORT = uint32(1);
global MIRcatSDK_RET_INITIALIZATION_FAILURE; MIRcatSDK_RET_INITIALIZATION_FAILURE = uint32(32);

global MIRcatSDK_RET_ARMDISARM_FAILURE; MIRcatSDK_RET_ARMDISARM_FAILURE = uint32(64);
global MIRcatSDK_RET_STARTTUNE_FAILURE; MIRcatSDK_RET_STARTTUNE_FAILURE = uint32(65);
global MIRcatSDK_RET_INTERLOCKS_KEYSWITCH_NOTSET; MIRcatSDK_RET_INTERLOCKS_KEYSWITCH_NOTSET = uint32(66);
global MIRcatSDK_RET_STOP_SCAN_FAILURE; MIRcatSDK_RET_STOP_SCAN_FAILURE = uint32(67);
global MIRcatSDK_RET_PAUSE_SCAN_FAILURE; MIRcatSDK_RET_PAUSE_SCAN_FAILURE = uint32(68);
global MIRcatSDK_RET_RESUME_SCAN_FAILURE; MIRcatSDK_RET_RESUME_SCAN_FAILURE = uint32(69);
global MIRcatSDK_RET_MANUAL_STEP_SCAN_FAILURE; MIRcatSDK_RET_MANUAL_STEP_SCAN_FAILURE = uint32(70);
global MIRcatSDK_RET_START_SWEEPSCAN_FAILURE; MIRcatSDK_RET_START_SWEEPSCAN_FAILURE = uint32(71);
global MIRcatSDK_RET_START_STEPMEASURESCAN_FAILURE; MIRcatSDK_RET_START_STEPMEASURESCAN_FAILURE = uint32(72);
global MIRcatSDK_RET_INDEX_OUTOFBOUNDS; MIRcatSDK_RET_INDEX_OUTOFBOUNDS = uint32(73);
global MIRcatSDK_RET_START_MULTISPECTRALSCAN_FAILURE; MIRcatSDK_RET_START_MULTISPECTRALSCAN_FAILURE = uint32(74);
global MIRcatSDK_RET_TOO_MANY_ELEMENTS; MIRcatSDK_RET_TOO_MANY_ELEMENTS = uint32(75);
global MIRcatSDK_RET_NOT_ENOUGH_ELEMENTS; MIRcatSDK_RET_NOT_ENOUGH_ELEMENTS = uint32(76);
global MIRcatSDK_RET_BUFFER_TOO_SMALL; MIRcatSDK_RET_BUFFER_TOO_SMALL = uint32(77);
global MIRcatSDK_RET_FAVORITE_NAME_NOTRECOGNIZED; MIRcatSDK_RET_FAVORITE_NAME_NOTRECOGNIZED = uint32(78);
global MIRcatSDK_RET_FAVORITE_RECALL_FAILURE;  MIRcatSDK_RET_FAVORITE_RECALL_FAILURE = uint32(79);
global MIRcatSDK_RET_WW_OUTOFTUNINGRANGE; MIRcatSDK_RET_WW_OUTOFTUNINGRANGE = uint32(80);
global MIRcatSDK_RET_NO_SCAN_INPROGRESS; MIRcatSDK_RET_NO_SCAN_INPROGRESS = uint32(81);
global MIRcatSDK_RET_EMISSION_ON_FAILURE; MIRcatSDK_RET_EMISSION_ON_FAILURE = uint32(82);
global MIRcatSDK_RET_EMISSION_ALREADY_OFF; MIRcatSDK_RET_EMISSION_ALREADY_OFF = uint32(83);
global MIRcatSDK_RET_EMISSION_OFF_FAILURE; MIRcatSDK_RET_EMISSION_OFF_FAILURE = uint32(84);
global MIRcatSDK_RET_EMISSION_ALREADY_ON; MIRcatSDK_RET_EMISSION_ALREADY_ON = uint32(85);
global MIRcatSDK_RET_PULSERATE_OUTOFRANGE; MIRcatSDK_RET_PULSERATE_OUTOFRANGE = uint32(86);
global MIRcatSDK_RET_PULSEWIDTH_OUTOFRANGE; MIRcatSDK_RET_PULSEWIDTH_OUTOFRANGE = uint32(87);
global MIRcatSDK_RET_CURRENT_OUTOFRANGE; MIRcatSDK_RET_CURRENT_OUTOFRANGE = uint32(88);
global MIRcatSDK_RET_SAVE_SETTINGS_FAILURE; MIRcatSDK_RET_SAVE_SETTINGS_FAILURE = uint32(89);
global MIRcatSDK_RET_QCL_NUM_OUTOFRANGE; MIRcatSDK_RET_QCL_NUM_OUTOFRANGE = uint32(90);
global MIRcatSDK_RET_LASER_ALREADY_ARMED; MIRcatSDK_RET_LASER_ALREADY_ARMED = uint32(91);
global MIRcatSDK_RET_LASER_ALREADY_DISARMED; MIRcatSDK_RET_LASER_ALREADY_DISARMED = uint32(92);
global MIRcatSDK_RET_LASER_NOT_ARMED; MIRcatSDK_RET_LASER_NOT_ARMED = uint32(93);
global MIRcatSDK_RET_LASER_NOT_TUNED; MIRcatSDK_RET_LASER_NOT_TUNED = uint32(94);
global MIRcatSDK_RET_TECS_NOT_AT_SET_TEMPERATURE; MIRcatSDK_RET_TECS_NOT_AT_SET_TEMPERATURE = uint32(95);
global MIRcatSDK_RET_CW_NOT_ALLOWED_ON_QCL; MIRcatSDK_RET_CW_NOT_ALLOWED_ON_QCL = uint32(96);
global MIRcatSDK_RET_INVALID_LASER_MODE; MIRcatSDK_RET_INVALID_LASER_MODE = uint32(97);
global MIRcatSDK_RET_TEMPERATURE_OUT_OF_RANGE; MIRcatSDK_RET_TEMPERATURE_OUT_OF_RANGE = uint32(98);
global MIRcatSDK_RET_LASER_POWER_OFF_ERROR; MIRcatSDK_RET_LASER_POWER_OFF_ERROR = uint32(99);
global MIRcatSDK_RET_COMM_ERROR; MIRcatSDK_RET_COMM_ERROR = uint32(100);
global MIRcatSDK_RET_NOT_INITIALIZED; MIRcatSDK_RET_NOT_INITIALIZED = uint32(101);
global MIRcatSDK_RET_ALREADY_CREATED; MIRcatSDK_RET_ALREADY_CREATED = uint32(102);
global MIRcatSDK_RET_START_SWEEP_ADVANCED_SCAN_FAILURE; MIRcatSDK_RET_START_SWEEP_ADVANCED_SCAN_FAILURE = uint32(103);
global MIRcatSDK_RET_INJECT_PROC_TRIG_ERROR; MIRcatSDK_RET_INJECT_PROC_TRIG_ERROR = uint32(104);

global MIRcatSDK_COMM_SERIAL; MIRcatSDK_COMM_SERIAL = uint8(1);
global MIRcatSDK_COMM_UDP; MIRcatSDK_COMM_UDP = uint8(2);
global MIRcatSDK_COMM_DEFAULT; MIRcatSDK_COMM_DEFAULT =MIRcatSDK_COMM_SERIAL;

global MIRcatSDK_SERIAL_PORT_AUTO; MIRcatSDK_SERIAL_PORT_AUTO = uint16(0);
global MIRcatSDK_SERIAL_BAUD_USE_DEFAULT; MIRcatSDK_SERIAL_BAUD_USE_DEFAULT = uint32(0);
global MIRcatSDK_SERIAL_BAUD1; MIRcatSDK_SERIAL_BAUD1 = uint16(115200);
global MIRcatSDK_SERIAL_BAUD2; MIRcatSDK_SERIAL_BAUD2 = uint16(921600);
global MIRcatSDK_UNITS_MICRONS; MIRcatSDK_UNITS_MICRONS = uint8(1); %so far the only variable left undefined
global MIRcatSDK_UNITS_CM1; MIRcatSDK_UNITS_CM1 = uint8(2);

global MIRcatSDK_MODE_ERROR; MIRcatSDK_MODE_ERROR = uint8(0);
global MIRcatSDK_MODE_PULSED; MIRcatSDK_MODE_PULSED = uint8(1);
global MIRcatSDK_MODE_CW; MIRcatSDK_MODE_CW = uint8(2);
global MIRcatSDK_MODE_CW_MOD; MIRcatSDK_MODE_CW_MOD = uint8(3);
global MIRcatSDK_MODE_CW_MR; MIRcatSDK_MODE_CW_MR =  uint8(6);	%currently not supported in firmware
global MIRcatSDK_MODE_CW_MR_MOD; MIRcatSDK_MODE_CW_MR_MOD = uint8(7);	%currently not supported in firmware
global MIRcatSDK_MODE_CW_FLTR1; MIRcatSDK_MODE_CW_FLTR1 = uint8(8);
global MIRcatSDK_MODE_CW_FLTR2; MIRcatSDK_MODE_CW_FLTR2 =  uint8(9);
global MIRcatSDK_MODE_CW_FLTR1_MOD; MIRcatSDK_MODE_CW_FLTR1_MOD =  uint8(10);

global MIRcatSDK_PROC_TRIG_MODE_INTERNAL; MIRcatSDK_PROC_TRIG_MODE_INTERNAL = uint8(1);
global MIRcatSDK_PROC_TRIG_MODE_EXTERNAL; MIRcatSDK_PROC_TRIG_MODE_EXTERNAL = uint8(2);
global MIRcatSDK_PROC_TRIG_MODE_MANUAL; MIRcatSDK_PROC_TRIG_MODE_MANUAL = uint8(3);

global MIRcatSDK_PULSE_MODE_INTERNAL; MIRcatSDK_PULSE_MODE_INTERNAL = uint8(1);
global MIRcatSDK_PULSE_MODE_EXTERNAL_TRIGGER; MIRcatSDK_PULSE_MODE_EXTERNAL_TRIGGER = uint8(2);
global MIRcatSDK_PULSE_MODE_EXTERNAL_PASSTHRU; MIRcatSDK_PULSE_MODE_EXTERNAL_PASSTHRU = uint8(3);
global MIRcatSDK_PULSE_MODE_WAVELENGTH_TRIGGER; MIRcatSDK_PULSE_MODE_WAVELENGTH_TRIGGER = uint8(4);

end